### ISSUE TITLE
Import not working on mobile browser

### ISSUE THREAD

**Issue by calgara12** [Ashenfactory/nuzlocke-tracker#3]
Hey, i just tried using your nuzlocke tracker. I really like it. Unfortunately the import doesnt work on my mobile browser.

I used Chrome on Android, also tried Brave, both did not work. It appears to do nothing after the warning if i really want to import the file.
Thanks in advance.

**Comment by Ashenfactory** [comment]
Thank you for the feedback!
I've tinkered around a little and seem to have gotten the import function working on Chrome for Android at least, but I'm hoping to fiddle a little more with how files are handled and give wider support for mobile browsers.
