### ISSUE TITLE
Rom hack support

### ISSUE THREAD

**Issue by dawnbomb** [Ashenfactory/nuzlocke-tracker#6]
A 'rom hack' button would be nice, that allows pokemon from every region to appear in any game, for those modders that add mons from other games to their romhacks that people want to nuzlock for some reason.

**Comment by Ashenfactory** [comment]
Thanks for your suggestion! I never properly responded to this, but I spent a lot of time thinking about the scope of these kinds of settings.
I've added a little settings button for each game that allows you to optionally disable the Dex limit for the currently selected game. I've also begun work on a feature that will allow you to add Pokémon (just names and a selection between some placeholder icons) to the dropdown menus.
